# Generated by Django 5.2.4 on 2025-10-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0003_rename_contestant_contestantoff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program0ff',
            new_name='ProgramOff',
        ),
    ]
