# Generated by Django 5.2.4 on 2025-09-26 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_program_is_group"),
    ]

    operations = [
    ]
