# Generated by Django 5.2.4 on 2025-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_program_members_count"),
    ]

    operations = [
    ]
