# Generated by Django 5.2.4 on 2026-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_participation_code_letter'),
    ]

    operations = [
    ]
