# Generated by Django 5.2.4 on 2025-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_competition_program_competition_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='competition_type',
            field=models.CharField(choices=[('MAIN', 'Main Campus'), ('OFF', 'Off Campus')], default='MAIN', max_length=10),
        ),
    ]
