# Generated by Django 5.2.4 on 2025-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_program_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_announced',
            field=models.BooleanField(default=False, help_text='Make results public'),
        ),
    ]
