# Generated by Django 5.2.4 on 2025-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_program_announced_at_program_is_announced'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='code_letter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
