# Generated by Django 5.2.4 on 2026-07-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemsetting'),
        ('core', '0028_systemsetting'),
    ]

    operations = [
    ]
