# Generated by Django 5.2.4 on 2026-07-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_0014_systemsetting_0028_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('STAGE', 'Stage Venue'), ('OFF_STAGE', 'Off-Stage Venue')], default='STAGE', max_length=15)),
                ('location_details', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['stage_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='buffer_margin_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Extra buffer time in minutes'),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_per_participant',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes per participant/group'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('STAGE', 'Stage Program'), ('OFF_STAGE', 'Off-Stage Program')], default='STAGE', max_length=15),
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_duration_minutes', models.PositiveIntegerField(default=0)),
                ('fest_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.festday')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.program')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.stage')),
            ],
            options={
                'ordering': ['fest_day__day_number', 'start_time'],
            },
        ),
    ]
